### PR TITLE
feat: comment + notes

### PR DESCRIPTION
**Pull request by nayyyhaa**
## In this PR :
- I've added comments + notes functionality to video lib.

**ONLY check the following files**

#### Components: 
- [x] [components/CommentBox.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-ee75423d99f45b17b90d5557ff6b7c0dd3a5bd78a435eb9f1d20f3cb39ddb8c4)
- [x] [components/Navbar.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-0b9e115b879d5389a7caf5029cd442d7358dbdeffd27469a478ad90752ed3d54)
- [x] [components/Note.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-3c01810d057a0bb7c7f9c539fbcfac251e5cc99c6b2a15ed543ff80105a4e280)
- [x] [components/NotesSidebar.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-056b27c6d7cbfe8700a726d679c0336d18b7a431718b6b660c176a6037ad1ed7)

#### Pages files

- [x] [pages/Homepage.js](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-1063f1bef92d5c0fee5f64413fed09584b31b2d9ab0873a1166a7a2f8294aa4c)
- [x] [pages/SingleVideoFeed.js](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-5140fd92ec91d9728026e6c752ef67bb91390440a27d1935a87ac2c65f5fa873)

 #### Contexts  + Reducers

- [x] [contexts/SearchContext.js](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-4e831c15dcc61b6b6362bc250420e3eb3d30e3130b5829943b7680e0b693938e)
- [x] [contexts/VideoContext.js](https://github.com/nayyyhaa/inNotion-watch/compare/comments-notes?expand=1#diff-c1e52d13641059b2a16e25f8f52c1adf5317cd64ba0f07d2571ec4c0d11f34b8)

#### files to *ignore*
- [ ] data files
- [ ] CSS files
- [ ] index files
- [ ] backend files

### CODE REVIEW

**Review by Dev-AkshatGupta — COMMENTED** [review]
I wanna know how are you handling the request for the comments since you are using the mock API and they don't have API for comments so how are you gonna handle that and also you don't made any change in the controllers too

**Comment by nayyyhaa** [comment]
> I wanna know how are you handling the request for the comments since you are using the mock API and they don't have API for comments so how are you gonna handle that and also you don't made any change in the controllers too

I'm handling comments state via Context API only, haven't integrated with backend yet.

**Comment by Dev-AkshatGupta** [comment]
> > I wanna know how are you handling the request for the comments since you are using the mock API and they don't have API for comments so how are you gonna handle that and also you don't made any change in the controllers too
> 
> I'm handling comments state via Context API only, haven't integrated with backend yet.

Cool then though you can use these if you want to

export const updateVideoHandler = function (schema, request) {
const { videoId } = request.params;
const { comments } = JSON.parse(request.requestBody);
        const video = schema.videos.findBy({ _id: videoId }).attrs;
        video.comments = comments;
const allVideos = this.db.videos;
this.db.videos.update({ _id: videoId }, { comments: comments });
        return new Response(200, {}, { video: { ...video } });
} catch (error) {
        return new Response(500, {}, { error });
    }
};

**Comment by Dev-AkshatGupta** [comment]
You can go ahead and merge it Kudos to you keep coding

**Review by vrx29 — APPROVED** [review]
everything looks good. The code is clean and functionality is also working perfectly fine. You can merge it.

**Comment by nayyyhaa** [comment]
Thanks @Dev-AkshatGupta & @vrx29 for reviewing. Merging the PR.

**Pull request merged**
