### PR TITLE
add: login/logout auth

### PR DESCRIPTION
**Pull request by nayyyhaa**
## In this PR :
- I've added auth pages to my video library.
- Added toast message from react-toastify

NOTE: only login/logout functionality has been added. It's currently not synced with liked, history, etc pages..

**ONLY check the following files**

### Files to check

- [x] [src/App.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67)

#### Components: 
- [x] [components/LoginForm.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-7a5d7b2ac64e1391b2ff94932aa39aa57a37aaf9c11c5e8749b57b6a5a8b55ee)
- [x] [/components/SignupForm.jsx](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-bbae46bf52ad87177ad5c45f22d7c383573891c53f8bbb76d7310cc3d6e9522d)

#### Pages files

- [x] [pages/Authorisation.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-61eac70e72073b41844d2b2abd9b7c31160f616e55e5ac0884361ad87c57347a)
- [x] [pages/ProfilePage.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-8f87910fb2d518acef30276ee347304b96916c28c629c92bc779a0422320cdc3)

 #### Contexts  + Reducers

- [x] [contexts/AuthContext.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-a8558bdda09a87ea852e53f4861f37246adfd6d1cbbb861d111ac240ccd62363)
- [x] [contexts/VideoContext.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-c1e52d13641059b2a16e25f8f52c1adf5317cd64ba0f07d2571ec4c0d11f34b8)

#### utils:
- [x] [custom-hooks/useAsync.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-985756c8311eea13d1632064a9584a3f2c56171a6293434bee966124ab8e5300)
- [x] [custom-hooks/useLogin.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-18301329ee0c0ef376dcb04d2fe5c8bfdf067e0837eeb4cc42d6ed8762ae07a1)
- [x] [services/authService.js](https://github.com/nayyyhaa/inNotion-watch/compare/auth-branch?expand=1#diff-f25a6b789a327778fdc64558c5e19e83ea1de617c3436e2a93aa6c9d69d716a1)

#### files to *ignore*
- [ ] data files
- [ ] CSS files
- [ ] index files
- [ ] files with only toastify integrated

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
good use of custom hooks for API calls and services for authentication. Use of `<Outlet />` in react router is also appreciated.

**Review by aayushjain-code — APPROVED** [review]
Everything looks goods Login with test credentials not working!

**Comment by nayyyhaa** [comment]
> Everything looks goods Login with test credentials not working!

Yes, forgot to add API_KEY to the netlify site. Now it's working fine. Thanks!

**Comment by nayyyhaa** [comment]
Made the said changes. Now merging the PR.

**Pull request merged**
